#!/bin/bash
set -e

# Define the list of directories to exclude (normalized to start with ./)
# These are derived from your Idea config list.
EXCLUDED_PATHS=(
  "./android_webview/" "./ash/" "./build/" "./buildtools/" "./cc/" "./chrome/"
  "./chromecast/" "./chromeos/" "./components/" "./content/" "./crypto/"
  "./device/" "./docs/" "./fuchsia_web/" "./google_apis/" "./gpu/" "./infra/"
  "./ios/" "./media/" "./native_client_sdk/" "./net/" "./out/" "./pdf/"
  "./skia/" "./testing/" "./ui/" "./v8/out/" "./v8/testing/"
  # Third party sub-directories
  "./third_party/abseil-cpp/" "./third_party/accessibility-audit/"
  "./third_party/accessibility_test_framework/" "./third_party/afl/"
  "./third_party/alsa/" "./third_party/amd/" "./third_party/android_build_tools/"
  "./third_party/android_deps/" "./third_party/android_media/"
  "./third_party/android_opengl/" "./third_party/android_platform/"
  "./third_party/android_prebuilts/" "./third_party/android_provider/"
  "./third_party/android_sdk/" "./third_party/android_swipe_refresh/"
  "./third_party/android_system_sdk/" "./third_party/android_toolchain/"
  "./third_party/android_tools_internal/" "./third_party/androidx/"
  "./third_party/androidx_javascriptengine/" "./third_party/angle/"
  "./third_party/anonymous_tokens/" "./third_party/aosp_dalvik/"
  "./third_party/apache-linux/" "./third_party/apache-portable-runtime/"
  "./third_party/apache-win32/" "./third_party/apple_apsl/"
  "./third_party/arcore-android-sdk/" "./third_party/arcore-android-sdk-client/"
  "./third_party/ashmem/" "./third_party/axe-core/" "./third_party/barhopper/"
  "./third_party/beto-core/" "./third_party/bidimapper/" "./third_party/blink/"
  "./third_party/boringssl/" "./third_party/breakpad/" "./third_party/brotli/"
  "./third_party/bspatch/" "./third_party/byte_buddy/" "./third_party/cardboard/"
  "./third_party/cast_core/" "./third_party/catapult/" "./third_party/ced/"
  "./third_party/checkstyle/" "./third_party/chevron/" "./third_party/chromevox/"
  "./third_party/chromite/" "./third_party/chromium-variations/"
  "./third_party/clang-format/" "./third_party/cld_3/" "./third_party/cldr/"
  "./third_party/closure_compiler/" "./third_party/cloud_authenticator/"
  "./third_party/colorama/" "./third_party/content_analysis_sdk/"
  "./third_party/coremltools/" "./third_party/cpu_features/" "./third_party/cpuinfo/"
  "./third_party/crabbyavif/" "./third_party/crashpad/" "./third_party/crc32c/"
  "./third_party/cronet_android_mainline_clang/" "./third_party/cros-components/"
  "./third_party/cros_system_api/" "./third_party/crossbench/" "./third_party/d3/"
  "./third_party/dav1d/" "./third_party/dawn/" "./third_party/dbus/"
  "./third_party/decklink/" "./third_party/depot_tools/" "./third_party/devscripts/"
  "./third_party/distributed_point_functions/" "./third_party/dom_distiller_js/"
  "./third_party/domato/" "./third_party/dpkg-shlibdeps/" "./third_party/eigen3/"
  "./third_party/emoji-metadata/" "./third_party/emoji-segmenter/"
  "./third_party/engflow-reclient-configs/" "./third_party/expat/"
  "./third_party/farmhash/" "./third_party/fast_float/" "./third_party/fdlibm/"
  "./third_party/ffmpeg/" "./third_party/fft2d/" "./third_party/flac/"
  "./third_party/flatbuffers/" "./third_party/flex/" "./third_party/fontconfig/"
  "./third_party/fp16/" "./third_party/freetype/" "./third_party/freetype-testing/"
  "./third_party/fuchsia-gn-sdk/" "./third_party/fuchsia-sdk/" "./third_party/fusejs/"
  "./third_party/fuzztest/" "./third_party/fxdiv/" "./third_party/gemmlowp/"
  "./third_party/gif_player/" "./third_party/glfw/" "./third_party/glslang/"
  "./third_party/google-closure-library/" "./third_party/google-java-format/"
  "./third_party/google-truth/" "./third_party/google_benchmark/"
  "./third_party/google_input_tools/" "./third_party/google_toolbox_for_mac/"
  "./third_party/google_trust_services/" "./third_party/googlefonts_testdata/"
  "./third_party/googletest/" "./third_party/gperf/" "./third_party/grpc/"
  "./third_party/grpc-java/" "./third_party/hamcrest/" "./third_party/harfbuzz-ng/"
  "./third_party/highway/" "./third_party/hunspell/" "./third_party/hunspell_dictionaries/"
  "./third_party/hyphenation-patterns/" "./third_party/iaccessible2/"
  "./third_party/iccjpeg/" "./third_party/icu/" "./third_party/icu4j/"
  "./third_party/ijar/" "./third_party/ink/" "./third_party/ink_stroke_modeler/"
  "./third_party/inspector_protocol/" "./third_party/instrumented_libs/"
  "./third_party/ipcz/" "./third_party/isimpledom/" "./third_party/jacoco/"
  "./third_party/javalang/" "./third_party/jdk/" "./third_party/jdk11/"
  "./third_party/jdk17/" "./third_party/jinja2/" "./third_party/jni_zero/"
  "./third_party/js_code_coverage/" "./third_party/jsoncpp/" "./third_party/jstemplate/"
  "./third_party/jszip/" "./third_party/junit/" "./third_party/khronos/"
  "./third_party/kotlin_stdlib/" "./third_party/kotlinc/" "./third_party/lcov/"
  "./third_party/lens_server_proto/" "./third_party/leveldatabase/"
  "./third_party/libFuzzer/" "./third_party/libaddressinput/" "./third_party/libaom/"
  "./third_party/libavif/" "./third_party/libbrlapi/" "./third_party/libc++/"
  "./third_party/libc++abi/" "./third_party/libdrm/" "./third_party/libei/"
  "./third_party/libevent/" "./third_party/libgav1/" "./third_party/libipp/"
  "./third_party/libjingle_xmpp/" "./third_party/libjpeg_turbo/"
  "./third_party/liblouis/" "./third_party/libphonenumber/"
  "./third_party/libprotobuf-mutator/" "./third_party/libsecret/"
  "./third_party/libsrtp/" "./third_party/libsync/" "./third_party/libtess2/"
  "./third_party/libunwind/" "./third_party/libunwindstack/"
  "./third_party/liburlpattern/" "./third_party/libusb/"
  "./third_party/libva_protected_content/" "./third_party/libvpx/"
  "./third_party/libwebm/" "./third_party/libwebp/" "./third_party/libx11/"
  "./third_party/libxcb-keysyms/" "./third_party/libxml/" "./third_party/libxslt/"
  "./third_party/libyuv/" "./third_party/libzip/" "./third_party/lighttpd/"
  "./third_party/lit/" "./third_party/llvm-build/" "./third_party/llvm-libc/"
  "./third_party/logdog/" "./third_party/logilab/" "./third_party/lottie/"
  "./third_party/lss/" "./third_party/lzma_sdk/" "./third_party/mako/"
  "./third_party/markdown/" "./third_party/markupsafe/"
  "./third_party/material_color_utilities/" "./third_party/material_design_icons/"
  "./third_party/material_web_components/" "./third_party/maven/"
  "./third_party/mediapipe/" "./third_party/mesa_headers/"
  "./third_party/metrics_proto/" "./third_party/microsoft_dxheaders/"
  "./third_party/microsoft_webauthn/" "./third_party/mig/" "./third_party/minigbm/"
  "./third_party/mockito/" "./third_party/modp_b64/" "./third_party/nan/"
  "./third_party/nasm/" "./third_party/nearby/" "./third_party/neon_2_sse/"
  "./third_party/netty-tcnative/" "./third_party/netty4/" "./third_party/ninja/"
  "./third_party/node/" "./third_party/nyx-packer/" "./third_party/ocmock/"
  "./third_party/omnibox_proto/" "./third_party/one_euro_filter/"
  "./third_party/openh264/" "./third_party/openscreen/" "./third_party/openxr/"
  "./third_party/opus/" "./third_party/ots/" "./third_party/pdfium/"
  "./third_party/pefile_py3/" "./third_party/perfetto/" "./third_party/perl/"
  "./third_party/pexpect/" "./third_party/pffft/" "./third_party/pipewire/"
  "./third_party/pipewire-media-session/" "./third_party/ply/"
  "./third_party/polymer/" "./third_party/private-join-and-compute/"
  "./third_party/private_membership/" "./third_party/protobuf/"
  "./third_party/protobuf-javascript/" "./third_party/pthreadpool/"
  "./third_party/puffin/" "./third_party/pycoverage/" "./third_party/pyelftools/"
  "./third_party/pyjson5/" "./third_party/pylint/" "./third_party/pywebsocket3/"
  "./third_party/pyyaml/" "./third_party/qcms/" "./third_party/quic_trace/"
  "./third_party/qunit/" "./third_party/r8/" "./third_party/rapidhash/"
  "./third_party/re2/" "./third_party/requests/" "./third_party/rjsmin/"
  "./third_party/rnnoise/" "./third_party/robolectric/" "./third_party/rust/"
  "./third_party/rust-toolchain/" "./third_party/ruy/" "./third_party/s2cellid/"
  "./third_party/screen-ai/" "./third_party/securemessage/"
  "./third_party/selenium-atoms/" "./third_party/sentencepiece/"
  "./third_party/shell-encryption/" "./third_party/simplejson/"
  "./third_party/sinonjs/" "./third_party/siso/" "./third_party/six/"
  "./third_party/skia/" "./third_party/smhasher/" "./third_party/snappy/"
  "./third_party/speech-dispatcher/" "./third_party/speedometer/"
  "./third_party/spirv-cross/" "./third_party/spirv-headers/"
  "./third_party/spirv-tools/" "./third_party/sqlite/" "./third_party/sqlite4java/"
  "./third_party/squirrel.mac/" "./third_party/subresource-filter-ruleset/"
  "./third_party/swift-toolchain/" "./third_party/swiftshader/"
  "./third_party/tensorflow-text/" "./third_party/tensorflow_models/"
  "./third_party/test_fonts/" "./third_party/text-fragments-polyfill/"
  "./third_party/tflite/" "./third_party/tflite_support/" "./third_party/turbine/"
  "./third_party/ukey2/" "./third_party/unrar/" "./third_party/updater/"
  "./third_party/usb_ids/" "./third_party/utf/" "./third_party/v4l-utils/"
  "./third_party/vulkan-deps/" "./third_party/vulkan-headers/"
  "./third_party/vulkan-loader/" "./third_party/vulkan-tools/"
  "./third_party/vulkan-utility-libraries/" "./third_party/vulkan-validation-layers/"
  "./third_party/vulkan_memory_allocator/" "./third_party/wayland/"
  "./third_party/wayland-protocols/" "./third_party/webdriver/"
  "./third_party/webgl/" "./third_party/webgpu-cts/" "./third_party/webpagereplay/"
  "./third_party/webrtc/" "./third_party/webrtc_overrides/"
  "./third_party/webxr_test_pages/" "./third_party/weston/" "./third_party/widevine/"
  "./third_party/win_build_output/" "./third_party/win_virtual_display/"
  "./third_party/wix/" "./third_party/wlcs/" "./third_party/woff2/"
  "./third_party/wpt_tools/" "./third_party/wtl/" "./third_party/wuffs/"
  "./third_party/x11proto/" "./third_party/xcbproto/" "./third_party/xdg-utils/"
  "./third_party/xnnpack/" "./third_party/zlib/" "./third_party/zstd/"
  "./third_party/zxcvbn-cpp/"
)

echo "Generating GN build"
# Note: Ensure the path to GN is correct for your system
/media/kishmakov/M2/vs/bn/src/buildtools/linux64/gn gen out/Fooo --args="import(\"//electron/build/args/testing.gn\")"

echo "Running ninja build to generate compile_commands_0.json"
ninja -C out/Fooo -t compdb cc cxx objc objcxx > compile_commands_0.json

echo "Filtering and modifying compile commands using jq"
# We pass the bash array as a JSON array using --argjson
jq --arg pwd "$PWD" --argjson excludes "$(printf '%s\n' "${EXCLUDED_PATHS[@]}" | jq -R . | jq -s .)" '
  map(
    # 1. First, normalize the file path like your original script
    .file |= sub("^\\.\\./\\.\\./"; "./") |
    .command |= (sub("^ccache +"; "") | sub("\\.\\./\\.\\./"; "./"; "g")) |
    .directory = $pwd
  )
  |
  # 2. Filter out any files that start with any of the excluded paths
  map(select(.file as $f | all($excludes[]; . as $ex | $f | startswith($ex) | not)))
' compile_commands_0.json > compile_commands.json

echo "Generated compile_commands.json with $(jq '. | length' compile_commands.json) entries"

echo "Cleaning up temporary files and build directory"
rm compile_commands_0.json
rm -r out/Fooo
